fhir docs config
Kuunika/Product-Master pull request #11
Opened 2020-09-08 08:20 UTC by Loui4

2020-09-08 16:58 UTC, danielmwakanema requested changes
It seems you have correctly setup the API document but forgotten to add the actual documentation to the controller.

2020-09-09 06:56 UTC, Loui4 commented
alright, let me do that.

2020-09-15 07:41 UTC, danielmwakanema approved these changes

2020-09-15 07:42 UTC, danielmwakanema commented
Looks good at the moment.

2020-09-15 07:42 UTC, merged